package V.DiviseParSections.App.SectionID9_AtelieModbile.Test.ID1

fun testDataproduitInfosList(): List<A_ProduitInfosTest> {
    return listOf(
        // Product 2: Tonner - Category 1 (Fun Candys)
        A_ProduitInfosTest(
            id = 54,
            nom = "Tonner®",
            nomArab = "اونير",
            prixVent = 500.0,
            prixAchat = 460.0,
            cartonState = "itsCarton",
            nomCategorie = "Fun Candys",
            couleur1 = "🍫 chocolat 🍫",
            nombreUniteInt = 60,
            nmbrCaron = 1,
            clientPrixVentUnite = 10.0,
            commmentSeVent = "U",
            diponibilityState = "",
            articleHaveUniteImages = false,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 1L // Fun Candys category
        ),

        // Product 3: golden sachet - Category 2 (Chocolattes)
        A_ProduitInfosTest(
            id = 565,
            nom = "golden sachet®",
            nomArab = "غولدن ساشي",
            prixVent = 4.0,
            prixAchat = 750.0,
            cartonState = "",
            nomCategorie = "Chocolattes 5 Da",
            couleur1 = "🟦 ازرق 🟦",
            couleur2 = "🟫 بني 🟫",
            nombreUniteInt = 200,
            nmbrCaron = 1,
            clientPrixVentUnite = 5.0,
            commmentSeVent = "",
            diponibilityState = "Non Dispo",
            articleHaveUniteImages = false,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 2L // Chocolattes category
        ),

        // Product 4: Mini Chips - Category 3 (شيبس)
        A_ProduitInfosTest(
            id = 567,
            nom = "Mini Chips®",
            nomArab = "ميني شيبس",
            prixVent = 410.0,
            prixAchat = 390.0,
            cartonState = "itsCarton",
            nomCategorie = "شيبس",
            couleur1 = "🧀 فرماج 🧀",
            couleur2 = "🧆 barbecu 🧆",
            nombreUniteInt = 100,
            nmbrCaron = 1,
            clientPrixVentUnite = 5.0,
            commmentSeVent = "",
            diponibilityState = "",
            articleHaveUniteImages = false,
            imageDimention = "Demi",
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 3L // شيبس category
        ),

        // Product 5: Jellopy Matrag - Category 4 (Jellies)
        A_ProduitInfosTest(
            id = 572,
            nom = "Jellopy Matrag®",
            nomArab = "",
            prixVent = 1710.0,
            prixAchat = 1650.0,
            cartonState = "UNITE",
            nomCategorie = "",
            couleur1 = "Standar",
            nombreUniteInt = 0,
            nmbrCaron = 0,
            clientPrixVentUnite = 0.0,
            commmentSeVent = "",
            diponibilityState = "Non Dispo",
            articleHaveUniteImages = true,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 4L // Jellies category
        ),

        // Product 6: TIZANA KBIR - Category 5 (ataye emballé)
        A_ProduitInfosTest(
            id = 3832,
            nom = "#TIZANA KBIR",
            nomArab = "",
            prixVent = 150.0,
            prixAchat = 150.0,
            cartonState = "",
            nomCategorie = "ataye emballé",
            nombreUniteInt = 0,
            nmbrCaron = 0,
            clientPrixVentUnite = 0.0,
            commmentSeVent = "",
            diponibilityState = "",
            articleHaveUniteImages = false,
            imageDimention = "",
            itsNewArrivale = false,
            timestamps = 1748355111768,
            needUpdate = true,
            affichageUniteState = false,
            benficeTotaleEntreMoiEtClien = -150.0,
            benificeClient = -150.0,
            benificeTotaleEn2 = -75.0,
            classementCate = -156.0,
            dateCreationCategorie = "1740564102869",
            funChangeImagsDimention = true,
            catalogeParentID = 0,
            lastUpdateState = "",
            neaon1 = 0.0,
            neaon2 = "",
            minQuan = 0,
            monBenfice = 0.0,
            afficheBoitSiUniter = null,
            autreNomDarticle = null,
            cLeDataOuvertDuParentList = false,
            idForSearchArticles = 0,
            idcolor1 = 0,
            idcolor2 = 0,
            idcolor3 = 0,
            idcolor4 = 0,
            couleur4 = null,
            nomCategorie2 = null,
            prixDeVentTotaleChezClient = 0.0,
            monPrixAchatUniter = 0.0,
            monPrixVentUniter = 0.0,
            monBeneficeUniter = 0.0,
            keyFireBase = "",
            idParentCategorie = 5L // ataye emballé category
        ),

        // Additional products to demonstrate grouping
        A_ProduitInfosTest(
            id = 1001,
            nom = "Extra Chocolate Bar",
            nomArab = "شوكولاتة إضافية",
            prixVent = 300.0,
            prixAchat = 250.0,
            cartonState = "itsCarton",
            nomCategorie = "Chocolattes 5 Da",
            couleur1 = "🍫 Dark 🍫",
            nombreUniteInt = 50,
            nmbrCaron = 1,
            clientPrixVentUnite = 6.0,
            commmentSeVent = "U",
            diponibilityState = "",
            articleHaveUniteImages = false,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 2L // Same as golden sachet (Chocolattes)
        ),

        A_ProduitInfosTest(
            id = 1002,
            nom = "Spicy Chips",
            nomArab = "شيبس حار",
            prixVent = 350.0,
            prixAchat = 320.0,
            cartonState = "itsCarton",
            nomCategorie = "شيبس",
            couleur1 = "🌶️ حار 🌶️",
            nombreUniteInt = 80,
            nmbrCaron = 1,
            clientPrixVentUnite = 4.5,
            commmentSeVent = "U",
            diponibilityState = "",
            articleHaveUniteImages = false,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = 3L // Same as Mini Chips (شيبس)
        ),

        // Product without category (will go to "Sans Catégorie")
        A_ProduitInfosTest(
            id = 1003,
            nom = "Uncategorized Item",
            nomArab = "عنصر غير مصنف",
            prixVent = 100.0,
            prixAchat = 80.0,
            cartonState = "",
            nomCategorie = "",
            couleur1 = "⚪ Standard ⚪",
            nombreUniteInt = 25,
            nmbrCaron = 1,
            clientPrixVentUnite = 4.0,
            commmentSeVent = "U",
            diponibilityState = "",
            articleHaveUniteImages = false,
            timestamps = System.currentTimeMillis(),
            needUpdate = true,
            idParentCategorie = null // No category - will be grouped under "Sans Catégorie"
        )
    )
}
